[tool.poetry]
name = "bouton_fuyant"
version = "0.1.0"
description = "Un projet Python avec tkinter où le bouton s'éloigne du curseur."
authors = ["VAlentin Videment, Maxouan Nion"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
tk = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
